#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nbsphinx
Version  : 0.4.3
Release  : 24
URL      : https://files.pythonhosted.org/packages/68/78/c517adc5015abb54aa4176c2b2667abb702d346a1dc39a018e2b5516508b/nbsphinx-0.4.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/68/78/c517adc5015abb54aa4176c2b2667abb702d346a1dc39a018e2b5516508b/nbsphinx-0.4.3.tar.gz
Summary  : Jupyter Notebook Tools for Sphinx
Group    : Development/Tools
License  : MIT
Requires: nbsphinx-license = %{version}-%{release}
Requires: nbsphinx-python = %{version}-%{release}
Requires: nbsphinx-python3 = %{version}-%{release}
Requires: Jinja2
Requires: Sphinx
Requires: docutils
Requires: nbconvert
Requires: nbformat
Requires: traitlets
BuildRequires : Jinja2
BuildRequires : Sphinx
BuildRequires : buildreq-distutils3
BuildRequires : docutils
BuildRequires : nbconvert
BuildRequires : nbformat
BuildRequires : traitlets
BuildRequires : util-linux

%description
Jupyter Notebook Tools for Sphinx
=================================
``nbsphinx`` is a Sphinx_ extension that provides a source parser for
``*.ipynb`` files.
Custom Sphinx directives are used to show `Jupyter Notebook`_ code cells (and of
course their results) in both HTML and LaTeX output.
Un-evaluated notebooks -- i.e. notebooks without stored output cells -- will be
automatically executed during the Sphinx build process.

%package license
Summary: license components for the nbsphinx package.
Group: Default

%description license
license components for the nbsphinx package.


%package python
Summary: python components for the nbsphinx package.
Group: Default
Requires: nbsphinx-python3 = %{version}-%{release}

%description python
python components for the nbsphinx package.


%package python3
Summary: python3 components for the nbsphinx package.
Group: Default
Requires: python3-core

%description python3
python3 components for the nbsphinx package.


%prep
%setup -q -n nbsphinx-0.4.3
cd %{_builddir}/nbsphinx-0.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1573839912
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nbsphinx
cp %{_builddir}/nbsphinx-0.4.3/LICENSE %{buildroot}/usr/share/package-licenses/nbsphinx/fc1aba20ab51a3917f89a3c11254221ed9cd9d9b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nbsphinx/fc1aba20ab51a3917f89a3c11254221ed9cd9d9b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
